// const Palettes= [
//     {
//       name: 'Flat Ui Palette',
//       paletteColors: [
//         { name: 'turquoise', color: '#1abc9c' },
//         { name: 'emerald', color: '#2ecc71' },
//         { name: 'peter river', color: '#3498db' },
//         { name: 'amethyst', color: '#9b59b6' },
//         { name: 'wet asphalt', color: '#34495e' },
//         { name: 'green sea', color: '#16a085' },
//         { name: 'nephritis', color: '#27ae60' },
//         { name: 'belize hole', color: '#2980b9' },
//         { name: 'wisteria', color: '#8e44ad' },
//         { name: 'midnight blue', color: '#2c3e50' },
//         { name: 'sun flower', color: '#f1c40f' },
//         { name: 'carrot', color: '#e67e22' },
//         { name: 'alizarin', color: '#e74c3c' },
//         { name: 'clouds', color: '#ecf0f1' },
//         { name: 'concrete', color: '#95a5a6' },
//         { name: 'orange', color: '#f39c12' },
//         { name: 'pumpkin', color: '#d35400' },
//         { name: 'pomegranate', color: '#c0392b' },
//         { name: 'silver', color: '#bdc3c7' },
//         { name: 'asbestos', color: '#7f8c8d' },
//       ],
//     },
//     {
//       name: 'American Palette',
//       paletteColors: [
//         { name: 'light greenish blue', color: '#55efc4' },
//         { name: 'faded poster', color: '#81ecec' },
//         { name: 'green darner tail', color: '#74b9ff' },
//         { name: 'shy moment', color: '#a29bfe' },
//         { name: 'city lights', color: '#dfe6e9' },
//         { name: 'mint leaf', color: '#00b894' },
//         { name: "robin's egg blue", color: '#00cec9' },
//         { name: 'electron blue', color: '#0984e3' },
//         { name: 'exodus fruit', color: '#0984e3' },
//         { name: 'soothing breeze', color: '#b2bec3' },
//         { name: 'sour lemon', color: '#ffeaa7' },
//         { name: 'first date', color: '#fab1a0' },
//         { name: 'pink glamour', color: '#ff7675' },
//         { name: 'pico-8-pink', color: '#fd79a8' },
//         { name: 'american river', color: '#636e72' },
//         { name: 'bright yarrow', color: '#fdcb6e' },
//         { name: 'orangeville', color: '#e17055' },
//         { name: 'chi-gong', color: '#d63031' },
//         { name: 'prunus avium', color: '#e84393' },
//         { name: 'dracula orchid', color: '#2d3436' },
//       ],
//     },
//     {
//       name: 'Aussie Palette',
//       paletteColors: [
//         { name: 'beekeeper', color: '#f6e58d' },
//         { name: 'spiced nectarine', color: '#ffbe76' },
//         { name: 'pink glamour', color: '#ff7979' },
//         { name: 'june bud', color: '#badc58' },
//         { name: 'costal breeze', color: '#dff9fb' },
//         { name: 'turbo', color: '#f9ca24' },
//         { name: 'quince jelly', color: '#f0932b' },
//         { name: 'carmine pink', color: '#eb4d4b' },
//         { name: 'pure apple', color: '#6ab04c' },

//         { name: 'hint of ice pack', color: '#c7ecee' },
//         { name: 'middle blue', color: '#7ed6df' },
//         { name: 'heliotrope', color: '#e056fd' },
//         { name: 'exodus fruit', color: '#686de0' },
//         { name: 'deep KOAMARU', color: '#30336b' },
//         { name: 'soaring eagle', color: '#95afc0' },
//         { name: 'greenland green', color: '#22a6b3' },
//         { name: 'steel pink', color: '#be2edd' },
//         { name: 'blurple', color: '#4834d4' },
//         { name: 'deep cove', color: '#130f40' },
//         { name: 'wizard grey', color: '#535c68' },
//       ],
//     },
//     {
//       name: 'British Palette',
//       paletteColors: [
//         { name: 'Protoss pylon', color: '#00a8ff' },
//         { name: 'periwinkle', color: '#9c88ff' },
//         { name: 'rise-n-shine', color: '#fbc531' },
//         { name: 'download progress', color: '#4cd137' },
//         { name: 'seabrook', color: '#487eb0' },
//         { name: 'vanadyl blue', color: '#0097e6' },
//         { name: 'matt purple', color: '#8c7ae6' },
//         { name: 'nanohancha gold', color: '#e1b12c' },
//         { name: 'skirret green', color: '#44bd32' },
//         { name: 'naval', color: '#40739e' },
//         { name: 'nasturcian flower', color: '#e84118' },
//         { name: 'lynx white', color: '#f5f6fa' },
//         { name: 'blueberry soda', color: '#7f8fa6' },
//         { name: 'mazarine blue', color: '#273c75' },
//         { name: 'blue nights', color: '#353b48' },
//         { name: 'harley davidson orange', color: '#c23616' },
//         { name: 'hint of pensive', color: '#dcdde1' },
//         { name: 'chain gang grey', color: '#718093' },
//         { name: 'pico void', color: '#192a56' },
//         { name: 'electromagnetic', color: '#2f3640' },
//       ],
//     },
//     {
//       name: 'Swidish Palette',
//       paletteColors: [
//         { name: 'Highlighter pink', color: '#ef5777' },
//         { name: 'dark periwinkle', color: '#575fcf' },
//         { name: 'megaman', color: '#0fbcf9' },
//         { name: 'fresh turquoise', color: '#34e7e4' },
//         { name: 'minty green', color: '#0be881' },
//         { name: 'sizzling red', color: '#f53b57' },
//         { name: 'free speech blue', color: '#3c40c6' },
//         { name: 'spiro disco ball', color: '#ff5e57' },
//         { name: 'jade dust', color: '#00d8d6' },
//         { name: 'green teal', color: '#05c46b' },
//         { name: 'narenji orange', color: '#ffc048' },
//         { name: 'yriel yellow', color: '#ffdd59' },
//         { name: 'sunset orange', color: '#ff3f34' },
//         { name: 'hint of elusive blue', color: '#d2dae2' },
//         { name: 'good night!', color: '#485460' },
//         { name: 'chrome yellow', color: '#ffa801' },
//         { name: 'vibrant yellow', color: '#ffd32a' },
//         { name: 'red orange', color: '#ff3f34' },
//         { name: 'london square', color: '#808e9b' },
//         { name: 'black pearl', color: '#1e272e' },
//       ],
//     },
//     {
//       name: 'Spanish Palette',
//       paletteColors: [
//         { name: 'Jacksons purple', color: '#40407a' },
//         { name: 'c64 purple', color: '#706fd3' },
//         { name: 'swan white', color: '#f7f1e3' },
//         { name: 'summer sky', color: '#34ace0' },
//         { name: 'celestial green', color: '#33d9b2' },
//         { name: 'lucky point', color: '#2c2c54' },
//         { name: 'liberty', color: '#474787' },
//         { name: 'hot stone', color: '#aaa69d' },
//         { name: 'devil blue', color: '#227093' },
//         { name: 'palm springs splash', color: '#218c74' },
//         { name: 'fluorescent red', color: '#ff5252' },
//         { name: 'synthetic pumpkin', color: '#ff793f' },
//         { name: 'crocodile tooth', color: '#d1ccc0' },
//         { name: 'mandarin sorbet', color: '#ffb142' },
//         { name: 'spiced butternut', color: '#ffda79' },
//         { name: 'eye of newt', color: '#b33939' },
//         { name: 'chilean fire', color: '#cd6133' },
//         { name: 'grey porcelain', color: '#84817a' },
//         { name: 'alameda ochre', color: '#cc8e35' },
//         { name: 'desert', color: '#ccae62' },
//       ],
//     },
//   ],

// pushData() {
//   for (let i = 0; i < this.Palettes.length; i++) {
//     axios
//       .post(
//         process.env.baseUrl + '/paletts.json',
//         /* what you wanna push in there */ {
//           ...this.Palettes[i],
//           id: slugify(this.Palettes[i].name, {
//             replacement: '-', // replace spaces with replacement character, defaults to `-`
//             remove: /[*+~.()'"!:@]/g, // remove characters that match regex, defaults to `undefined`
//             lower: true, // convert to lower case, defaults to `false`
//             strict: true, // strip special characters except replacement, defaults to `false`
//           }),
//         }
//       )
//       .then((res) => console.log(res.data))
//       .catch((e) => console.log(e))
//   }
// },
